
platform :ios, '13.5'

inhibit_all_warnings!

workspace 'fitnes.xcworkspace'

project 'TrainingProgramm/TrainingProgramm.xcodeproj'
project 'fitnes.xcodeproj'
project 'PrototypingProject/PrototypingProject.xcodeproj'

target 'fitnes' do
  project 'fitnes.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fitnes
  pod 'FSCalendar'
  pod 'SwiftGen', '~> 6.0'

end

target 'TrainingProgramm' do
  project 'TrainingProgramm/TrainingProgramm.xcodeproj'
  pod 'SwiftGen', '~> 6.0'
end

target 'PrototypingProject' do
  project 'PrototypingProject/PrototypingProject.xcodeproj'
  pod 'SwiftGen', '~> 6.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('13.5') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.5'
      end
    end
  end
  
  # This removes the warning about swift conversion, hopefuly forever!
  # https://github.com/CocoaPods/CocoaPods/issues/8674
  installer.pods_project.root_object.attributes['LastSwiftMigration'] = 9999
  installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = 9999
  installer.pods_project.root_object.attributes['LastUpgradeCheck'] = 9999
  
end
