//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ErrorResponseWithMessage: APIModel {

    public var message: String

    public init(message: String) {
        self.message = message
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        message = try container.decode("message")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(message, forKey: "message")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ErrorResponseWithMessage else { return false }
      guard self.message == object.message else { return false }
      return true
    }

    public static func == (lhs: ErrorResponseWithMessage, rhs: ErrorResponseWithMessage) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
