//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class TrainingsList: APIModel {

    public var message: [Training]

    public init(message: [Training]) {
        self.message = message
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        message = try container.decodeArray("message")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(message, forKey: "message")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? TrainingsList else { return false }
      guard self.message == object.message else { return false }
      return true
    }

    public static func == (lhs: TrainingsList, rhs: TrainingsList) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
