//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class UserRegistrationResponseErrorWithMessage: APIModel {

    public enum Message: String, Codable, Equatable, CaseIterable {
        case userExist = "User exist"
    }

    public var message: Message

    public init(message: Message) {
        self.message = message
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        message = try container.decode("message")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(message, forKey: "message")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? UserRegistrationResponseErrorWithMessage else { return false }
      guard self.message == object.message else { return false }
      return true
    }

    public static func == (lhs: UserRegistrationResponseErrorWithMessage, rhs: UserRegistrationResponseErrorWithMessage) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
