//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class UserRegistrationResponseOtherError: APIModel {

    public enum UserId: String, Codable, Equatable, CaseIterable {
        case lessThannullgreaterThan = "<null>"
    }

    public var message: String

    public var userId: UserId

    public init(message: String, userId: UserId) {
        self.message = message
        self.userId = userId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        message = try container.decode("message")
        userId = try container.decode("user_id")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(message, forKey: "message")
        try container.encode(userId, forKey: "user_id")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? UserRegistrationResponseOtherError else { return false }
      guard self.message == object.message else { return false }
      guard self.userId == object.userId else { return false }
      return true
    }

    public static func == (lhs: UserRegistrationResponseOtherError, rhs: UserRegistrationResponseOtherError) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
