//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension FitnessAPI {

    /** Get List of trainings */
    public enum GetTrainingsListByTrainerId {

        public static let service = APIService<Response>(id: "getTrainingsListByTrainerId", tag: "", method: "GET", path: "/api/v1/trainings", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** value should be bearer: #{token_id} */
                public var authorization: String

                /** Id of trainer */
                public var trainerId: Int?

                public init(authorization: String, trainerId: Int? = nil) {
                    self.authorization = authorization
                    self.trainerId = trainerId
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetTrainingsListByTrainerId.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(authorization: String, trainerId: Int? = nil) {
                let options = Options(authorization: authorization, trainerId: trainerId)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let trainerId = options.trainerId {
                  params["trainer_id"] = trainerId
                }
                return params
            }

            override var headerParameters: [String: String] {
                var headers: [String: String] = [:]
                headers["authorization"] = options.authorization
                return headers
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = TrainingsList

            /** List of trainings */
            case status200(TrainingsList)

            public var success: TrainingsList? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(TrainingsList.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
